# Site settings
title: Chobitly
email: chobitly@gmail.com
description: > # this means to ignore newlines until "baseurl:" 
Google Plus Page: https://plus.google.com/+%E6%B1%AA%E7%92%90chobitly
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://chobitly.github.io" # the base hostname & protocol for your site
twitter_username: chobitly
github_username:  chobitly
gplus_username:   汪璐chobitly

# Build settings
markdown: kramdown
